# This is a sample Drone config file for a 'vanilla' build consisting of a single Docker container
#   deployed via Rancher to test and prod servers.
# It should be named '.drone.yml' and be in the repo's root folder.
# Things you'll definitely need to change are in FIXME comments below.

kind: pipeline
type: docker
name: default


steps:
# First, do whatever pre-build steps you need to do...running unit tests, packing JS/CSS assets, whatever.
#- name: prebuild
#  image: ubuntu
#  pull: always
#  commands:
# FIXME actually do those steps here.
#  - echo "Build steps, such as compiling assets via NPM, go here."


# Build the test version of the Docker container and publish it to a given tag.
# Do this only for commits to the git 'master' branch.
- name: build
  image: plugins/docker
  pull: always
  settings:
    username: 
      from_secret: dockerhub_username
    password: 
      from_secret: dockerhub_token
# FIXME change this Docker image name
    repo: docker-registry.la.utexas.edu/texas_beyond_history
    tags:
    - 'drone-${DRONE_BUILD_NUMBER}'
  when:
    event:
    - cron
    cron:
    - nightly


# Deploy the test image you just built to the test server
- name: deploy_test
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_token:                                                                   
      from_secret: kubernetes_token
    kubernetes_server:                                                    
      from_secret: kubernetes_server
    namespace: tbh-test
    deployment: web
    container: web
    repo: docker-registry.la.utexas.edu/texas_beyond_history
    tag: drone-${DRONE_BUILD_NUMBER}
  when:
    event:
    - cron
    cron:
    - nightly



# Deploy the image you just built
#- name: deploy_prod
#  image: quay.io/honestbee/drone-kubernetes
#  settings:
#    kubernetes_token:                                                                   
#      from_secret: kubernetes_token
#    kubernetes_server:                                                    #
#      from_secret: kubernetes_server
#    namespace: NAMESPACE_HERE
#    deployment: WORKLOAD_HERE
#    container: WORKLOAD_HERE
#    repo: docker-registry.la.utexas.edu/REPONAME
#    tag: drone-${DRONE_BUILD_NUMBER}
#  when:
#    ref:
#    - refs/tags/release-*

image_pull_secrets:
- dockerconfig